**Data Exploration**

In [ ]:
import os
import pandas as pd
import numpy as np

# 1. Configuration
REPO_URL = "https://github.com/kavee2002nr-ux/database_assignment.git"
REPO_NAME = "database_assignment"

# 2. Clone the repository
# Adding a check so it doesn't try to clone twice if run the cell again
if not os.path.exists(REPO_NAME):
    print(f"Cloning repository: {REPO_NAME}...")
    !git clone {REPO_URL}
else:
    print(f"Repository already exists at /content/{REPO_NAME}")

# 3. Move into the repository folder
os.chdir(f'/content/{REPO_NAME}')

# 4. Verify the data path
data_path = 'data/raw'
if os.path.exists(data_path):
    print(f"\nData found! Found {len(os.listdir(data_path))} files.")

    # 5. Automatically load the CSVs into variables

    for file in os.listdir(data_path):
        if file.endswith('.csv'):
            var_name = file.replace('.csv', '')
            globals()[var_name] = pd.read_csv(os.path.join(data_path, file))
            print(f"   - {file} loaded as '{var_name}'")
else:
    print("Error: Cannot find 'data/raw'. Check your folder names on GitHub.")

Repository already exists at /content/database_assignment

Data found! Found 11 files.
   - data_dictionary.csv loaded as 'data_dictionary'
   - hubs.csv loaded as 'hubs'
   - complaints.csv loaded as 'complaints'
   - drivers.csv loaded as 'drivers'
   - customers.csv loaded as 'customers'
   - orders.csv loaded as 'orders'
   - incidents.csv loaded as 'incidents'
   - vehicles.csv loaded as 'vehicles'
   - deliveries.csv loaded as 'deliveries'
   - app_events.csv loaded as 'app_events'

**Loading datasets in Colab**

In [ ]:
# Cell 2: Check uploaded files
import os
print("Uploaded files:", os.listdir())

Uploaded files: ['outputs', 'requirements', 'data', 'notebooks', 'README.md', '.git', 'database_assignment', 'mongodb', 'report']

**Data Understanding**

In [ ]:
# --- STEP 1: INITIAL PROFILING ---
#  check the first few rows and summary info for the core operational files
print("--- Deliveries Summary ---")
print(deliveries.info())
print("\n--- Missing Values Check ---")
# This addresses the "missing values" requirement
for name, df in {'deliveries': deliveries, 'vehicles': vehicles, 'complaints': complaints}.items():
    missing = df.isnull().sum().sum()
    print(f"{name}: {missing} missing values")

# --- STEP 2: IDENTIFY INCONSISTENCIES ---
# The brief mentions "inconsistent categorical values"
print("\n--- Checking for Inconsistent Categories in Deliveries ---")
print(deliveries['delivery_status'].unique())

# --- STEP 3: CROSS-FILE RELATIONSHIP CHECK ---
# Checking if 'order_id' exists in both orders and deliveries [cite: 111]
common_orders = set(orders['order_id']).intersection(set(deliveries['order_id']))
print(f"\nRelationship Check: Found {len(common_orders)} matching orders between Orders and Deliveries.")

--- Deliveries Summary ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB
None

--- Missing Values Check ---
deliveries: 33 missing values
vehicles: 4 missing values
complaints: 16 missing values

--- Checking for Inconsistent Categories in Deliveries ---
['Failed' 'OnTime' 'Delayed']

Relationship Check: Found 950 matching orders between Orders and Deliveries.

**Display and verify all uploaded datasets.**

In [ ]:
# Display all loaded dataset names

loaded_datasets = [
    'app_events',
    'complaints',
    'customers',
    'data_dictionary',
    'deliveries',
    'drivers',
    'hubs',
    'incidents',
    'orders',
    'vehicles'
]

print("Loaded datasets:\n")

for dataset in loaded_datasets:
    print(f" {dataset}")

Loaded datasets:

 app_events
 complaints
 customers
 data_dictionary
 deliveries
 drivers
 hubs
 incidents
 orders
 vehicles

**Data Exploration**

In [ ]:
# Create a dictionary for easier processing
datasets = {
    'complaints': complaints,
    'app_events': app_events,
    'customers': customers,
    'data_dictionary': data_dictionary,
    'deliveries': deliveries,
    'drivers': drivers,
    'hubs': hubs,
    'incidents': incidents,
    'orders': orders,
    'vehicles': vehicles
}
# Dataset shapes
print("DATASET SHAPES")
print("=" * 50)
for name, df in datasets.items():
    print(f"{name}: {df.shape[0]} rows, {df.shape[1]} columns")

# Display columns of each dataset
print("COLUMN NAMES")
print("=" * 50)
for name, df in datasets.items():
    print(f"\n{name.upper()} COLUMNS:")
    print(df.columns.tolist())

# Display datatypes
print("DATA TYPES")
print("=" * 50)

for name, df in datasets.items():
    print(f"\n{name.upper()} DATA TYPES:")
    print(df.dtypes)

# Preview first 5 rows
for name, df in datasets.items():
    print(f"\n{name.upper()} SAMPLE RECORDS")
    print("=" * 50)
    display(df.head())

# Display detailed dataset information
for name, df in datasets.items():
    print(f"\n{name.upper()} INFO")
    print("=" * 60)
    df.info()

DATASET SHAPES
==================================================
complaints: 320 rows, 10 columns
app_events: 640 rows, 10 columns
customers: 650 rows, 9 columns
data_dictionary: 9 rows, 3 columns
deliveries: 950 rows, 13 columns
drivers: 170 rows, 8 columns
hubs: 8 rows, 5 columns
incidents: 280 rows, 7 columns
orders: 1250 rows, 11 columns
vehicles: 120 rows, 8 columns
COLUMN NAMES
==================================================

COMPLAINTS COLUMNS:
['complaint_id', 'customer_id', 'order_id', 'complaint_type', 'channel', 'severity', 'created_at', 'status', 'resolution_days', 'compensation_amount']

APP_EVENTS COLUMNS:
['event_id', 'customer_id', 'order_id', 'event_timestamp', 'event_type', 'session_id', 'device_type', 'zone_context', 'api_latency_ms', 'success_flag']

CUSTOMERS COLUMNS:
['customer_id', 'age', 'home_zone', 'customer_type', 'signup_date', 'loyalty_score', 'app_engagement_score', 'preferred_channel', 'account_status']

DATA_DICTIONARY COLUMNS:
['file_name', 'record_count', 'description']

DELIVERIES COLUMNS:
['delivery_id', 'order_id', 'driver_id', 'vehicle_id', 'hub_id', 'dispatch_time', 'delivery_completed_at', 'delivery_status', 'route_distance_km', 'manual_route_override_count', 'proof_of_completion_missing', 'customer_rating_post_delivery', 'fuel_or_charge_cost']

DRIVERS COLUMNS:
['driver_id', 'base_zone', 'employment_type', 'years_experience', 'training_score', 'driver_rating', 'shift_preference', 'active_flag']

HUBS COLUMNS:
['hub_id', 'hub_name', 'zone', 'hub_type', 'capacity_score']

INCIDENTS COLUMNS:
['incident_id', 'delivery_id', 'incident_type', 'reported_at', 'severity', 'resolution_status', 'resolved_hours']

ORDERS COLUMNS:
['order_id', 'customer_id', 'service_type', 'order_created_at', 'promised_window_hours', 'pickup_zone', 'dropoff_zone', 'priority_level', 'order_value', 'booking_channel', 'special_handling_flag']

VEHICLES COLUMNS:
['vehicle_id', 'vehicle_type', 'assigned_zone', 'commission_date', 'battery_health_pct', 'odometer_km', 'maintenance_status', 'telematics_version']
DATA TYPES
==================================================

COMPLAINTS DATA TYPES:
complaint_id            object
customer_id             object
order_id                object
complaint_type          object
channel                 object
severity                object
created_at              object
status                  object
resolution_days          int64
compensation_amount    float64
dtype: object

APP_EVENTS DATA TYPES:
event_id           object
customer_id        object
order_id           object
event_timestamp    object
event_type         object
session_id         object
device_type        object
zone_context       object
api_latency_ms      int64
success_flag        int64
dtype: object

CUSTOMERS DATA TYPES:
customer_id              object
age                       int64
home_zone                object
customer_type            object
signup_date              object
loyalty_score           float64
app_engagement_score    float64
preferred_channel        object
account_status           object
dtype: object

DATA_DICTIONARY DATA TYPES:
file_name       object
record_count     int64
description     object
dtype: object

DELIVERIES DATA TYPES:
delivery_id                       object
order_id                          object
driver_id                         object
vehicle_id                        object
hub_id                            object
dispatch_time                     object
delivery_completed_at             object
delivery_status                   object
route_distance_km                float64
manual_route_override_count        int64
proof_of_completion_missing        int64
customer_rating_post_delivery    float64
fuel_or_charge_cost              float64
dtype: object

DRIVERS DATA TYPES:
driver_id            object
base_zone            object
employment_type      object
years_experience      int64
training_score      float64
driver_rating       float64
shift_preference     object
active_flag           int64
dtype: object

HUBS DATA TYPES:
hub_id            object
hub_name          object
zone              object
hub_type          object
capacity_score     int64
dtype: object

INCIDENTS DATA TYPES:
incident_id           object
delivery_id           object
incident_type         object
reported_at           object
severity              object
resolution_status     object
resolved_hours       float64
dtype: object

ORDERS DATA TYPES:
order_id                  object
customer_id               object
service_type              object
order_created_at          object
promised_window_hours      int64
pickup_zone               object
dropoff_zone              object
priority_level            object
order_value              float64
booking_channel           object
special_handling_flag      int64
dtype: object

VEHICLES DATA TYPES:
vehicle_id             object
vehicle_type           object
assigned_zone          object
commission_date        object
battery_health_pct    float64
odometer_km             int64
maintenance_status     object
telematics_version     object
dtype: object

COMPLAINTS SAMPLE RECORDS
==================================================

,complaint_id,customer_id,order_id,complaint_type,channel,severity,created_at,status,resolution_days,compensation_amount
0,CP0001,C0464,O00814,AppIssue,App,High,2025-03-30 02:36:00,Open,11,23.99
1,CP0002,C0056,O00628,MissedPickup,Phone,Medium,2024-11-07 10:05:00,Open,4,21.64
2,CP0003,C0469,O00384,Delay,Chatbot,High,2024-01-02 15:47:00,Open,16,26.41
3,CP0004,C0631,O00406,Delay,App,Medium,2025-01-14 13:07:00,AwaitingCustomer,7,23.44
4,CP0005,C0535,O00154,Delay,Email,Medium,2024-08-31 05:56:00,Resolved,1,16.18

APP_EVENTS SAMPLE RECORDS
==================================================

,event_id,customer_id,order_id,event_timestamp,event_type,session_id,device_type,zone_context,api_latency_ms,success_flag
0,AE00001,C0488,NaN,2024-08-09 03:25:00,eta_refresh,S19847,Android,north,301,1
1,AE00002,C0595,O00950,2024-02-13 22:29:00,search_route,S32766,Android,SOUTH,60,1
2,AE00003,C0494,O00170,2025-08-11 09:29:00,chat_opened,S99516,iOS,Airport,1118,1
3,AE00004,C0407,O00756,2025-08-23 17:38:00,eta_refresh,S41236,iOS,CENTRAL,442,1
4,AE00005,C0506,NaN,2024-05-29 10:33:00,search_route,S12030,iOS,north,60,1

CUSTOMERS SAMPLE RECORDS
==================================================

,customer_id,age,home_zone,customer_type,signup_date,loyalty_score,app_engagement_score,preferred_channel,account_status
0,C0001,26,North,SME,2024-11-27 04:25:00,44.9,69.2,App,Active
1,C0002,61,AIRPORT,Consumer,2025-10-28 01:04:00,55.4,66.6,App,Active
2,C0003,66,East,Consumer,2025-07-02 03:23:00,75.9,33.8,NaN,Active
3,C0004,75,CENTRAL,Consumer,2025-08-19 01:58:00,32.5,33.0,App,Active
4,C0005,26,Riverside,Consumer,2025-06-03 06:02:00,55.9,100.0,Web,Active

DATA_DICTIONARY SAMPLE RECORDS
==================================================

,file_name,record_count,description
0,hubs.csv,8,Operational hubs and control points
1,customers.csv,650,Customer master data with engagement and loyal...
2,drivers.csv,170,Driver workforce data with training and rating...
3,vehicles.csv,120,Fleet asset data including battery and mainten...
4,orders.csv,1250,Service orders across mobility and logistics o...

DELIVERIES SAMPLE RECORDS
==================================================

,delivery_id,order_id,driver_id,vehicle_id,hub_id,dispatch_time,delivery_completed_at,delivery_status,route_distance_km,manual_route_override_count,proof_of_completion_missing,customer_rating_post_delivery,fuel_or_charge_cost
0,DL00001,O00938,D004,V056,H05,2024-06-18 10:57:00,2024-06-19 09:05:59.904311,Failed,17.26,1,0,3.07,12.05
1,DL00002,O00004,D138,V007,H02,2025-01-11 18:45:00,2025-01-11 17:39:00.000000,OnTime,10.34,1,0,5.00,13.41
2,DL00003,O00639,D006,V049,H02,2025-06-02 20:39:00,2025-06-02 21:45:32.366770,OnTime,7.92,0,0,4.98,8.51
3,DL00004,O00313,D116,V055,H02,2024-03-08 23:31:00,2024-03-09 23:30:08.103702,Delayed,16.42,0,0,4.18,13.62
4,DL00005,O00844,D108,V034,H01,2025-09-21 11:43:00,2025-09-21 15:45:34.131056,OnTime,14.52,1,0,4.18,9.22

DRIVERS SAMPLE RECORDS
==================================================

,driver_id,base_zone,employment_type,years_experience,training_score,driver_rating,shift_preference,active_flag
0,D001,AIRPORT,FullTime,8,67.8,3.54,Morning,1
1,D002,Central,FullTime,4,42.4,3.94,Evening,1
2,D003,AIRPORT,FullTime,11,96.5,5.00,Evening,1
3,D004,Airport,PartTime,13,88.9,4.75,Morning,1
4,D005,north,FullTime,3,69.7,4.14,Morning,1

HUBS SAMPLE RECORDS
==================================================

  hub_id        hub_name     zone   hub_type  capacity_score
0    H01  North Exchange    North   Dispatch              82
1    H02      South Link    South   Dispatch              78
2    H03       East Dock     East  Warehouse              74
3    H04       West Gate     West   Dispatch              69
4    H05    Central Core  Central    Control              88

INCIDENTS SAMPLE RECORDS
==================================================

,incident_id,delivery_id,incident_type,reported_at,severity,resolution_status,resolved_hours
0,I0001,DL00221,BatteryAlert,2024-03-11 23:46:00,Medium,Escalated,12.3
1,I0002,DL00578,BatteryAlert,2024-02-21 10:56:00,Low,Open,9.6
2,I0003,DL00175,TemperatureIssue,2025-04-17 23:22:00,Medium,Open,22.0
3,I0004,DL00417,ProofMissing,2025-02-09 00:16:00,Medium,Closed,9.8
4,I0005,DL00897,RouteDeviation,2025-01-04 02:49:00,Low,Open,13.0

ORDERS SAMPLE RECORDS
==================================================

,order_id,customer_id,service_type,order_created_at,promised_window_hours,pickup_zone,dropoff_zone,priority_level,order_value,booking_channel,special_handling_flag
0,O00001,C0292,Passenger,2024-08-20 14:43:00,6,Airport,South,Medium,126.65,App,0
1,O00002,C0459,Passenger,2024-05-14 22:16:00,24,North,AIRPORT,Low,109.30,App,0
2,O00003,C0161,Passenger,2025-09-02 14:37:00,4,West,AIRPORT,High,33.50,Phone,0
3,O00004,C0520,Parcel,2025-01-11 17:15:00,2,RiverSide,North,Medium,10.04,App,1
4,O00005,C0558,Retail,2025-02-17 19:32:00,12,Riverside,SOUTH,Low,125.58,Phone,0

VEHICLES SAMPLE RECORDS
==================================================

,vehicle_id,vehicle_type,assigned_zone,commission_date,battery_health_pct,odometer_km,maintenance_status,telematics_version
0,V001,EV,North,2024-12-28 23:48:00,71.8,56928,Active,v2.2
1,V002,EV,AIRPORT,2024-04-21 16:14:00,67.9,159368,InRepair,v2.2
2,V003,CargoVan,north,2025-11-24 23:59:00,91.7,219359,Active,v2.1
3,V004,Hybrid,RiverSide,2024-06-07 13:21:00,NaN,36310,Active,v2.2
4,V005,CargoVan,West,2025-11-15 11:08:00,58.6,146638,Active,v2.2

COMPLAINTS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 320 entries, 0 to 319
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   complaint_id         320 non-null    object
 1   customer_id          320 non-null    object
 2   order_id             320 non-null    object
 3   complaint_type       320 non-null    object
 4   channel              320 non-null    object
 5   severity             320 non-null    object
 6   created_at           320 non-null    object
 7   status               320 non-null    object
 8   resolution_days      320 non-null    int64
 9   compensation_amount  304 non-null    float64
dtypes: float64(1), int64(1), object(8)
memory usage: 25.1+ KB

APP_EVENTS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 640 entries, 0 to 639
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   event_id         640 non-null    object
 1   customer_id      640 non-null    object
 2   order_id         496 non-null    object
 3   event_timestamp  640 non-null    object
 4   event_type       640 non-null    object
 5   session_id       640 non-null    object
 6   device_type      640 non-null    object
 7   zone_context     640 non-null    object
 8   api_latency_ms   640 non-null    int64
 9   success_flag     640 non-null    int64
dtypes: int64(2), object(8)
memory usage: 50.1+ KB

CUSTOMERS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 650 entries, 0 to 649
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   customer_id           650 non-null    object
 1   age                   650 non-null    int64
 2   home_zone             650 non-null    object
 3   customer_type         650 non-null    object
 4   signup_date           650 non-null    object
 5   loyalty_score         630 non-null    float64
 6   app_engagement_score  650 non-null    float64
 7   preferred_channel     637 non-null    object
 8   account_status        650 non-null    object
dtypes: float64(2), int64(1), object(6)
memory usage: 45.8+ KB

DATA_DICTIONARY INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   file_name     9 non-null      object
 1   record_count  9 non-null      int64
 2   description   9 non-null      object
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes

DELIVERIES INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   delivery_id                    950 non-null    object
 1   order_id                       950 non-null    object
 2   driver_id                      950 non-null    object
 3   vehicle_id                     950 non-null    object
 4   hub_id                         950 non-null    object
 5   dispatch_time                  950 non-null    object
 6   delivery_completed_at          931 non-null    object
 7   delivery_status                950 non-null    object
 8   route_distance_km              950 non-null    float64
 9   manual_route_override_count    950 non-null    int64
 10  proof_of_completion_missing    950 non-null    int64
 11  customer_rating_post_delivery  936 non-null    float64
 12  fuel_or_charge_cost            950 non-null    float64
dtypes: float64(3), int64(2), object(8)
memory usage: 96.6+ KB

DRIVERS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170 entries, 0 to 169
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   driver_id         170 non-null    object
 1   base_zone         170 non-null    object
 2   employment_type   170 non-null    object
 3   years_experience  170 non-null    int64
 4   training_score    163 non-null    float64
 5   driver_rating     170 non-null    float64
 6   shift_preference  170 non-null    object
 7   active_flag       170 non-null    int64
dtypes: float64(2), int64(2), object(4)
memory usage: 10.8+ KB

HUBS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   hub_id          8 non-null      object
 1   hub_name        8 non-null      object
 2   zone            8 non-null      object
 3   hub_type        8 non-null      object
 4   capacity_score  8 non-null      int64
dtypes: int64(1), object(4)
memory usage: 452.0+ bytes

INCIDENTS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   incident_id        280 non-null    object
 1   delivery_id        280 non-null    object
 2   incident_type      280 non-null    object
 3   reported_at        280 non-null    object
 4   severity           280 non-null    object
 5   resolution_status  280 non-null    object
 6   resolved_hours     263 non-null    float64
dtypes: float64(1), object(6)
memory usage: 15.4+ KB

ORDERS INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1250 entries, 0 to 1249
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               1250 non-null   object
 1   customer_id            1250 non-null   object
 2   service_type           1250 non-null   object
 3   order_created_at       1250 non-null   object
 4   promised_window_hours  1250 non-null   int64
 5   pickup_zone            1250 non-null   object
 6   dropoff_zone           1250 non-null   object
 7   priority_level         1250 non-null   object
 8   order_value            1250 non-null   float64
 9   booking_channel        1225 non-null   object
 10  special_handling_flag  1250 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 107.6+ KB

VEHICLES INFO
============================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   vehicle_id          120 non-null    object
 1   vehicle_type        120 non-null    object
 2   assigned_zone       120 non-null    object
 3   commission_date     120 non-null    object
 4   battery_health_pct  116 non-null    float64
 5   odometer_km         120 non-null    int64
 6   maintenance_status  120 non-null    object
 7   telematics_version  120 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 7.6+ KB

**Error analysis in Datasets**

In [ ]:
import pandas as pd
import numpy as np
import os

# 1. Setup paths for the processed data
processed_path = 'data/processed'
if not os.path.exists(processed_path):
    os.makedirs(processed_path)

print("--- SECTION 2: STARTING DATA CLEANING & PREPARATION ---\n")

# 2. Standardize Categories & Remove Duplicates (Global Function)
def initial_clean(df):
    # Remove exact duplicate rows
    df = df.drop_duplicates()
    # Standardize text: lowercase and strip whitespace
    for col in df.select_dtypes(include=['object']).columns:
        df[col] = df[col].astype(str).str.lower().str.strip()
    return df

# Apply initial cleaning to all loaded dataframes
app_events = initial_clean(app_events)
complaints = initial_clean(complaints)
customers = initial_clean(customers)
deliveries = initial_clean(deliveries)
drivers = initial_clean(drivers)
hubs = initial_clean(hubs)
incidents = initial_clean(incidents)
orders = initial_clean(orders)
vehicles = initial_clean(vehicles)

# 3. Fix Missing Values (Imputation)
# Battery Health: Fill with median to avoid outliers
vehicles['battery_health_pct'] = pd.to_numeric(vehicles['battery_health_pct'], errors='coerce')
vehicles['battery_health_pct'] = vehicles['battery_health_pct'].fillna(vehicles['battery_health_pct'].median())

# Customer Rating: Fill with mean
deliveries['customer_rating_post_delivery'] = pd.to_numeric(deliveries['customer_rating_post_delivery'], errors='coerce')
deliveries['customer_rating_post_delivery'] = deliveries['customer_rating_post_delivery'].fillna(deliveries['customer_rating_post_delivery'].mean())

# 4. Convert Dates/Times
# This is crucial for calculating delays and operational patterns
deliveries['dispatch_time'] = pd.to_datetime(deliveries['dispatch_time'], errors='coerce')
deliveries['delivery_completed_at'] = pd.to_datetime(deliveries['delivery_completed_at'], errors='coerce')
orders['order_created_at'] = pd.to_datetime(orders['order_created_at'], errors='coerce')

# 5. Create Engineered Features (The "Analytical" part)
# Feature A: Delivery Duration in Minutes
deliveries['delivery_duration_mins'] = (deliveries['delivery_completed_at'] - deliveries['dispatch_time']).dt.total_seconds() / 60

# Feature B: Delay Flag (If duration is longer than the promised window in orders)
#  merge briefly to calculate this
order_windows = orders[['order_id', 'promised_window_hours']].copy()
deliveries = deliveries.merge(order_windows, on='order_id', how='left')
deliveries['proof_of_completion_missing'] = np.where(deliveries['delivery_duration_mins'] > (deliveries['promised_window_hours'] * 60), 1, 0)

# Feature C: Troubleshooting App Events (Count events per order/customer)
event_counts = app_events.groupby('customer_id').size().reset_index(name='total_app_interactions')
customers = customers.merge(event_counts, on='customer_id', how='left').fillna(0)

# 6. Save Cleaned Datasets
cleaned_files = {
    'app_events': app_events, 'complaints': complaints, 'customers': customers,
    'deliveries': deliveries, 'drivers': drivers, 'hubs': hubs,
    'incidents': incidents, 'orders': orders, 'vehicles': vehicles
}

print("Exporting cleaned data to /data/processed...")
for name, df in cleaned_files.items():
    path = os.path.join(processed_path, f"{name}_cleaned.csv")
    df.to_csv(path, index=False)
    print(f" - {name}_cleaned.csv saved.")

print("\n--- DATA CLEANING COMPLETE ---")

--- SECTION 2: STARTING DATA CLEANING & PREPARATION ---

Exporting cleaned data to /data/processed...
 - app_events_cleaned.csv saved.
 - complaints_cleaned.csv saved.
 - customers_cleaned.csv saved.
 - deliveries_cleaned.csv saved.
 - drivers_cleaned.csv saved.
 - hubs_cleaned.csv saved.
 - incidents_cleaned.csv saved.
 - orders_cleaned.csv saved.
 - vehicles_cleaned.csv saved.

--- DATA CLEANING COMPLETE ---

**Dataset verification**

In [ ]:
# Final verification
import os
processed_path = 'data/processed'
if os.path.exists(processed_path):
    print("Cleaned files successfully created:")
    print(os.listdir(processed_path))
else:
    print("ERROR: Processed folder not found.")

Cleaned files successfully created:
['deliveries_cleaned.csv', 'complaints_cleaned.csv', '.gitkeep', 'vehicles_cleaned.csv', 'incidents_cleaned.csv', 'drivers_cleaned.csv', 'hubs_cleaned.csv', 'app_events_cleaned.csv', 'orders_cleaned.csv', 'customers_cleaned.csv']

**Saving the cleaned data to Github**

In [ ]:

USER_NAME = "kavee2002nr-ux"
ENUM_REPO = "database_assignment"
TOKEN = "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"

# Create the authenticated URL
remote_url = f"https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{ENUM_REPO}.git"

# Set the remote URL and push
!git remote set-url origin {remote_url}
!git push origin main

Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 2 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (13/13), 106.94 KiB | 3.45 MiB/s, done.
Total 13 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/kavee2002nr-ux/database_assignment.git
   235ce7c..cad96e8  main -> main